(function(){
'use strict';
const mode=(location.pathname||'').toLowerCase().includes('express')?'Career Express':'Original Career';
const state=()=>{try{return window.GameV3?.state?.()||null}catch(e){return null}};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
function hash(v){let h=2166136261>>>0;for(const c of String(v)){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0}
function peak(s){return Math.max(s.player?.rating||0,...(s.player?.seasons||[]).map(x=>Number(x.ratingAfter||x.ratingBefore||0)))}
function trophies(s){return s.player?.career?.trophies||[]}
function awards(s){return s.player?.career?.awards||[]}
function records(s){const direct=s.player?.career?.records||[];if(direct.length)return direct;const out=[];for(const [club,row] of Object.entries(s.clubRecordsBroken||{}))for(const [type,done] of Object.entries(row||{}))if(done)out.push({id:`${club}|${type}`,club,type,label:type==='apps'?'Appearance record':type==='goals'?'Goals record':'Assist record',year:'Career'});return out}
function hardScore(s){const p=s.player,c=p.career||{},seasons=p.seasons?.length||0,pk=peak(s),ts=trophies(s),as=awards(s),rs=records(s),major=ts.filter(x=>/Champions League|World Cup|Copa Libertadores/i.test(x)).length,ballons=as.filter(x=>/Ballon d'Or/i.test(x)).length,caps=p.international?.caps||0,ga=(c.goals||0)+(c.assists||0),target=p.position==='GK'?1:['CB','FB','DM'].includes(p.position)?300:p.position==='CM'?560:980,ability=clamp((pk-58)/38*20,0,20),longevity=clamp((c.apps||0)/900*10,0,10)+clamp(seasons/24*4,0,4),output=p.position==='GK'?clamp((c.apps||0)/900*18,0,18):clamp(ga/target*18,0,18),team=clamp(ts.length*.9+major*1.8,0,16),individual=clamp(as.length*.72+ballons*3.1,0,18),intl=clamp(caps/125*6+(p.international?.trophies||[]).filter(x=>/World Cup/i.test(x)).length*2,0,8),recordPoints=clamp(rs.length*2.1,0,6),raw=ability+longevity+output+team+individual+intl+recordPoints,perfect=pk>=96&&(c.apps||0)>=780&&major>=4&&ballons>=3&&as.length>=11&&ts.length>=15&&rs.length>=1&&raw>=96;return perfect?100:clamp(Math.round(raw),0,99)}
function scoreLabel(n){return n===100?'Football Immortal':n>=94?'Historic Great':n>=86?'World Great':n>=76?'World Class':n>=64?'Elite Career':n>=50?'Outstanding Professional':n>=36?'Respected Professional':'A Career Earned'}
function recordPanel(s){const rows=records(s);return `<div class="card flV6Records" id="flV6Records"><div class="eyebrow">CLUB RECORDS</div><h3>Records that belong to you</h3>${rows.length?rows.map(r=>`<div class="flV6RecordRow"><b>📜 ${esc(r.club)} • ${esc(r.label||r.type)}</b><span>${Number.isFinite(r.value)?`${r.value} • `:''}${typeof r.year==='number'?`Broken in ${r.year}/${String(r.year+1).slice(-2)}`:'Career record'}</span></div>`).join(''):'<div class="flV6Empty">No club records broken yet.</div>'}</div>`}
function bestSeason(s){return (s.player.seasons||[]).slice().sort((a,b)=>(b.avg+(b.trophies?.length||0)*.15+(b.awards?.length||0)*.12)-(a.avg+(a.trophies?.length||0)*.15+(a.awards?.length||0)*.12))[0]}
function analysisPanel(s){if(!s.player?.retired)return '';const p=s.player,c=p.career||{},h=p.seasons||[],best=bestSeason(s),clubs=[...new Set(h.map(x=>x.club).filter(Boolean))],score=hardScore(s),beat=peak(s)-(p.originalPotential||p.potential||peak(s)),historic=h.filter(x=>x.historicSeason),rows=[['Career arc',beat>0?`The original potential forecast was beaten by ${beat}. The ceiling moved because the performances demanded it.`:`The career rose to a peak of ${peak(s)} OVR and finished with a ${p.potential} potential forecast.`],['Peak season',best?`${best.label} at ${best.club}: ${best.stats.apps} apps, ${best.stats.goals} goals, ${best.stats.assists} assists and a ${best.avg.toFixed(2)} average.`:'No complete season was recorded.'],['Club journey',`${clubs.length} club${clubs.length===1?'':'s'} across ${h.length} seasons. ${records(s).length?`${records(s).length} club record${records(s).length===1?' was':'s were'} broken.`:'No club record was taken.'}`],['Honours',`${trophies(s).length} trophies and ${awards(s).length} individual awards. ${historic.length?`${historic.length} once-in-an-era season${historic.length===1?' produced':'s produced'} extraordinary figures.`:'The career stayed within the normal statistical range.'}`]];if(mode==='Original Career')rows.push(['International career',`${p.international?.caps||0} caps and ${p.international?.goals||0} goals for ${p.nationality}.`],['Historical standing',`${score}/100 • ${scoreLabel(score)}. The score weighs peak, longevity, output, major honours, international success and club records.`]);else rows.push(['Final verdict',`${score}/100 • ${scoreLabel(score)}. A perfect 100 now demands an almost complete all-time career.`]);return `<div class="card flV6Analysis" id="flV6Analysis"><div class="eyebrow">FINAL CAREER ANALYSIS • ${esc(mode.toUpperCase())}</div><div class="flV6LegacyScore">${score}/100</div><h2>${esc(scoreLabel(score))}</h2>${rows.map(([a,b])=>`<div class="flV6AnalysisRow"><b>${esc(a)}</b><span>${esc(b)}</span></div>`).join('')}</div>`}
function updateFinalCard(s){const card=document.getElementById('flFinalShare');if(!card)return;const score=hardScore(s),strong=card.querySelector('.flFinalScore strong'),title=card.querySelector('h2');if(strong)strong.textContent=score;if(title)title.textContent=scoreLabel(score);const share=card.querySelector('.flShareText');if(share)share.textContent=`FOOTBALL LEGACY — ${mode}\n${s.player.name} • ${s.player.nationality} • ${s.player.position}\n${s.player.seasons?.length||0} seasons • Peak ${peak(s)} OVR • Legacy ${score}/100\n${s.player.career.apps||0} apps • ${s.player.career.goals||0} goals • ${s.player.career.assists||0} assists\n${trophies(s).length} trophies • ${awards(s).length} awards • ${records(s).length} club records`}
function injectCareer(){const s=state(),box=document.getElementById('screen-career');if(!s?.player||!box)return;if(!box.querySelector('#flV6Records'))box.insertAdjacentHTML('beforeend',recordPanel(s));if(s.player.retired&&!box.querySelector('#flV6Analysis'))box.insertAdjacentHTML('afterbegin',analysisPanel(s));updateFinalCard(s)}
function historicRoll(){const s=state(),season=s?.season?.reviewData?.season;if(!s?.player||!season||season.flHistoricChecked)return;season.flHistoricChecked=true;const p=s.player,profile=Number(p.historicProfile||0),rarity={common:0,uncommon:.0001,rare:.0004,epic:.0012,legendary:.004,mythic:.012}[p.rarity]||0,prob=clamp(.00025+profile+rarity,0,.065),roll=hash(`${s.seed}|${season.label}|historic`)/4294967296;if(p.age<20||p.age>34||p.rating<85||season.stats.apps<24||season.avg<6.98||roll>=prob)return;const oldG=season.stats.goals||0,oldA=season.stats.assists||0,seed=hash(`${s.seed}|${season.label}|figures`),total=42+seed%27;if(['ST','WG','AM'].includes(p.position)){const g=p.position==='ST'?Math.round(total*.66):Math.round(total*.51);season.stats.goals=Math.max(oldG,g);season.stats.assists=Math.max(oldA,total-g)}else if(['CM','DM','FB'].includes(p.position)){const t=27+seed%20;season.stats.goals=Math.max(oldG,Math.round(t*.32));season.stats.assists=Math.max(oldA,t-Math.round(t*.32))}season.stats.apps=Math.max(season.stats.apps,40+seed%8);season.avg=Math.max(season.avg,+(7.95+(seed%66)/100).toFixed(2));p.career.apps+=season.stats.apps-(s.season.stats.apps||season.stats.apps);p.career.goals+=season.stats.goals-oldG;p.career.assists+=season.stats.assists-oldA;s.season.stats={...s.season.stats,...season.stats};season.historicSeason=true;s.news?.unshift?.({year:s.year,text:`🌠 ${p.name} produces a once-in-an-era season: ${season.stats.goals} goals and ${season.stats.assists} assists.`});setTimeout(()=>window.GameV3?.openScreen?.('season'),20)}
function prestige(text){if(/Ballon|The Best FIFA|World Cup|Champions League|Yashin|Kopa|Gerd Müller/i.test(text))return 4;if(/Europa|Conference|Premier League|La Liga|Bundesliga|Serie A|Ligue 1|World 11|European Golden Shoe/i.test(text))return 3;if(/Golden|Player of the Season|Defender|Midfielder|champion|winner|trophy/i.test(text))return 2;return 1}
function decorateFlash(){const flash=document.getElementById('flash'),card=document.getElementById('flashCard');if(!flash?.classList.contains('show')||!card)return;const text=card.textContent||'';if(!/award|winner|champion|trophy|ballon|record/i.test(text))return;const key=text.slice(0,120);if(card.dataset.flDrama===key)return;card.dataset.flDrama=key;card.classList.remove('flPrestige1','flPrestige2','flPrestige3','flPrestige4');card.classList.add(`flPrestige${prestige(text)}`);card.querySelector('.flCeremonyRain')?.remove();const rain=document.createElement('div');rain.className='flCeremonyRain';rain.innerHTML=Array.from({length:prestige(text)*9},(_,i)=>`<i style="--x:${(i*41)%98}%;--d:${1.5+(i%7)*.23}s;--delay:-${(i%9)*.19}s"></i>`).join('');card.prepend(rain)}
function showRecordCeremony(){const s=state(),pending=s?.pendingRecordCelebrations;if(!s?.season?.reviewPending||!pending?.length||document.querySelector('.flRecordCeremony'))return;const fresh=pending.filter(r=>!(s.flShownRecordIds||[]).includes(r.id));if(!fresh.length){s.pendingRecordCelebrations=[];return}s.flShownRecordIds??=[];s.flShownRecordIds.push(...fresh.map(r=>r.id));s.pendingRecordCelebrations=[];const layer=document.createElement('div');layer.className='flRecordCeremony';layer.setAttribute('role','dialog');layer.setAttribute('aria-modal','true');layer.innerHTML=`<div class="flRecordStage"><div class="flRecordKicker">CLUB HISTORY HAS CHANGED</div><div class="flRecordIcon">📜</div><h2>Club record broken</h2><p>${esc(s.player.name)} now owns ${fresh.map(r=>`${r.club}’s ${String(r.label).toLowerCase()}`).join(' and ')}.</p><button id="flRecordContinue">Back to Play Career</button></div>`;document.body.appendChild(layer);document.getElementById('flRecordContinue').onclick=()=>{layer.remove();window.GameV3?.openScreen?.('home')}}
function enhance(){historicRoll();showRecordCeremony();injectCareer();decorateFlash()}
new MutationObserver(()=>requestAnimationFrame(enhance)).observe(document.body,{childList:true,subtree:true,attributes:true,attributeFilter:['class']});document.addEventListener('click',()=>setTimeout(enhance,35),true);setInterval(enhance,1200);setTimeout(enhance,100);
window.FL_CAREER_DRAMA={hardScore,scoreLabel,records};
})();
