(function(){
'use strict';
const $=s=>document.querySelector(s),screens=[...document.querySelectorAll('.mpScreen')],MAX_PLAYERS=6,MAX_SEASONS=10,ROOM_PREFIX='football-legacy-room-';
let peer=null,hostConnection=null,connections=new Map(),isHost=false,myPeerId='',myName='',localState=null,choiceSent=false,selectedChoice=null,statusTimer=null,revealTimer=null,cinematicRun=0;
const POS_LABEL={ST:'Striker',WG:'Winger',CM:'Central Midfielder',CB:'Centre Back',GK:'Goalkeeper'};
const POINTS={goal:10,assist:10,domesticCup:250,leagueTitle:500,continentalClub:800,internationalCountry:1100,ballonDor:1200};
const AWARD_POINTS={'Breakthrough Award':120,'Team of the Season':180,'Golden Boot':350,'Player of the Season':450};
const CLUBS=[
 {name:'Hometown FC',tier:62},{name:'Brighton & Hove Albion',tier:77},{name:'Benfica',tier:81},{name:'Bayer Leverkusen',tier:84},{name:'Borussia Dortmund',tier:86},{name:'Arsenal',tier:89},{name:'Inter Milan',tier:89},{name:'Liverpool',tier:91},{name:'Bayern Munich',tier:92},{name:'Paris Saint-Germain',tier:92},{name:'Manchester City',tier:94},{name:'Barcelona',tier:94},{name:'Real Madrid',tier:95}
];
const PROFILES=[
 {name:'Patient Prospect',rarity:'common',chance:17,w:170,ovr:[58,61],pot:[76,82],growth:.94},{name:'First-Team Project',rarity:'common',chance:16,w:160,ovr:[59,62],pot:[78,84],growth:.98},{name:'Steady Foundation',rarity:'common',chance:15,w:150,ovr:[60,63],pot:[80,85],growth:1},{name:'Physical Riser',rarity:'common',chance:10,w:100,ovr:[59,63],pot:[79,86],growth:1.02},{name:'Hidden Upside',rarity:'uncommon',chance:9,w:90,ovr:[59,62],pot:[82,88],growth:1.04},{name:'Late Spark',rarity:'uncommon',chance:7.5,w:75,ovr:[57,61],pot:[81,89],growth:.97},{name:'Big-Match Talent',rarity:'uncommon',chance:6,w:60,ovr:[61,64],pot:[82,89],growth:1.04},{name:'Reinvention Path',rarity:'uncommon',chance:4.5,w:45,ovr:[59,64],pot:[80,91],growth:1.01},{name:'Accelerated Rise',rarity:'rare',chance:4.5,w:45,ovr:[63,66],pot:[86,92],growth:1.10},{name:'High-Ceiling Wildcard',rarity:'rare',chance:3.5,w:35,ovr:[61,66],pot:[85,94],growth:1.08},{name:'Elite Tools',rarity:'rare',chance:3,w:30,ovr:[64,67],pot:[89,94],growth:1.12},{name:'Relentless Prodigy',rarity:'epic',chance:2.2,w:22,ovr:[65,68],pot:[91,96],growth:1.17,historic:.004},{name:'Golden Generation Talent',rarity:'epic',chance:1,w:10,ovr:[66,69],pot:[93,97],growth:1.20,historic:.008},{name:'Generational Outlier',rarity:'legendary',chance:.7,w:7,ovr:[67,70],pot:[95,99],growth:1.25,historic:.018},{name:'Unwritten Ceiling',rarity:'mythic',chance:.1,w:1,ovr:[68,71],pot:[96,99],growth:1.29,historic:.045}
];
const SCENARIOS=[
 {icon:'🏋️',title:'The extra session',text:'The coaches offer one final training block before the season.',options:[{label:'Push to the limit',hint:'High upside. Less control.',base:.22,swing:.78,dev:.42},{label:'Train with purpose',hint:'Balanced progress.',base:.28,swing:.42,dev:.25},{label:'Protect your fitness',hint:'Safer season. Smaller leap.',base:.18,swing:.23,apps:2}]},
 {icon:'🎙️',title:'The pressure question',text:'A reporter asks whether you can become the face of the club.',options:[{label:'Promise a huge season',hint:'Bold. The pressure rises.',base:.18,swing:.72,award:.04},{label:'Let football answer',hint:'Calm and balanced.',base:.26,swing:.38,award:.015},{label:'Praise the whole team',hint:'Safer spotlight. Slight team boost.',base:.17,swing:.24,trophy:.025}]},
 {icon:'👕',title:'The shirt is available',text:'A bigger squad role is there, but only if you demand it now.',options:[{label:'Demand to start',hint:'More games if it works.',base:.18,swing:.67,apps:5},{label:'Earn it quietly',hint:'Steady trust.',base:.27,swing:.36,apps:2},{label:'Focus on development',hint:'Fewer games. More growth.',base:.20,swing:.31,apps:-2,dev:.48}]},
 {icon:'✈️',title:'A major transfer call',text:'A stronger club wants you. The move could raise your ceiling, but your role may shrink.',transfer:true,options:[{label:'Accept the move',hint:'Higher club level. More trophy upside, tougher competition.',base:.16,swing:.70,transfer:true,apps:-2,trophy:.055},{label:'Demand a bigger role',hint:'The best outcome is huge. The deal can also collapse.',base:.12,swing:.92,transfer:true,apps:2,trophy:.035},{label:'Stay and lead',hint:'More security and minutes at your current club.',base:.27,swing:.34,apps:4,trophy:.015}]},
 {icon:'🧊',title:'The body feels heavy',text:'The schedule is building and one choice must be made.',options:[{label:'Play through it',hint:'More matches. More risk.',base:.10,swing:.73,apps:4},{label:'Use a managed plan',hint:'Balanced recovery.',base:.27,swing:.34,apps:1},{label:'Take a full reset',hint:'Fewer games. Better form odds.',base:.22,swing:.42,apps:-3,dev:.18}]},
 {icon:'©️',title:'The captain looks at you',text:'The dressing room needs someone to speak before a decisive run.',options:[{label:'Take command',hint:'Leadership can lift the whole season.',base:.23,swing:.62,trophy:.04,award:.02},{label:'Lead through actions',hint:'Reliable influence.',base:.29,swing:.35,award:.01},{label:'Stay focused on yourself',hint:'Personal upside. Team risk.',base:.13,swing:.61,dev:.31,attack:.12}]},
 {icon:'🎯',title:'The tactical gamble',text:'The manager offers you freedom in the biggest matches.',options:[{label:'Attack every opening',hint:'Explosive but volatile.',base:.20,swing:.80,attack:.42},{label:'Choose your moments',hint:'Controlled influence.',base:.29,swing:.40,attack:.20},{label:'Keep the team shape',hint:'Safer team outcome.',base:.21,swing:.25,trophy:.05}]},
 {icon:'📄',title:'The contract deadline',text:'Your club wants an answer before the season begins.',options:[{label:'Sign immediately',hint:'Security and trust.',base:.23,swing:.31,apps:2},{label:'Negotiate hard',hint:'Bigger upside, more distraction.',base:.17,swing:.73,award:.025},{label:'Run the deal down',hint:'Risk the season for a route to a bigger move.',base:.13,swing:.84,transfer:true,apps:-1}]},
 {icon:'🌍',title:'The international summer',text:'Club preparation clashes with a chance to impress for your country.',options:[{label:'Chase the tournament',hint:'Global stage. Heavy workload.',base:.20,swing:.68,international:.055,award:.035},{label:'Balance both camps',hint:'The measured route.',base:.28,swing:.37,international:.02},{label:'Prioritise the club',hint:'Better domestic preparation.',base:.22,swing:.27,apps:2,trophy:.03}]},
 {icon:'🔥',title:'The final season begins',text:'Ten years have led to one last chance to define the career.',options:[{label:'Risk everything',hint:'The highest ceiling and lowest floor.',base:.22,swing:.92,attack:.48,award:.06,trophy:.035},{label:'Trust the complete game',hint:'A balanced final push.',base:.32,swing:.42,trophy:.04,award:.025},{label:'Protect the legacy',hint:'Secure what you have.',base:.20,swing:.20,apps:2}]}
];
function hash(v){let h=2166136261>>>0;for(const c of String(v)){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0}
function rng(key){return hash(key)/4294967296}
function rint(key,a,b){return a+Math.floor(rng(key)*(b-a+1))}
function clamp(n,a,b){return Math.max(a,Math.min(b,n))}
function cleanName(v){return String(v||'').replace(/[^\p{L}\p{N} ._'-]/gu,'').trim().slice(0,18)}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function initials(v){return String(v||'?').split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase()}
function code(){const chars='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';return Array.from({length:5},()=>chars[Math.floor(Math.random()*chars.length)]).join('')}
function setScreen(id){screens.forEach(x=>x.classList.toggle('active',x.id===id))}
function notice(text,error=false){const el=$('#connectionStatus');el.textContent=text;el.className=`mpStatus show${error?' error':''}`;clearTimeout(statusTimer);statusTimer=setTimeout(()=>el.className='mpStatus',2600)}
function weightedProfile(roomCode,gameNo=0){let q=(hash(roomCode+'|profile|'+gameNo)%1000)+1;for(const p of PROFILES){q-=p.w;if(q<=0)return p}return PROFILES[0]}
function clubTier(name){return CLUBS.find(c=>c.name===name)?.tier||70}
function publicRoom(){if(!localState)return null;const showChoices=['breakdown','leaderboard','final'].includes(localState.phase);return {...localState,players:localState.players.map(p=>({...p,ready:p.choice!=null,choice:showChoices?p.choice:null})),results:localState.results||[]}}
function send(conn,msg){try{if(conn?.open)conn.send(msg)}catch(e){}}
function broadcast(msg){for(const conn of connections.values())send(conn,msg)}
function publish(){if(!isHost)return;const payload={type:'state',room:publicRoom()};broadcast(payload);render()}
function makePlayer(id,name,profile){return {id,name,connected:true,choice:null,age:17,ovr:profile.startOvr,pot:profile.startPot,peak:profile.startOvr,club:'Hometown FC',apps:0,goals:0,assists:0,trophies:{domesticCup:0,leagueTitle:0,continentalClub:0,internationalCountry:0},awards:[],ballonDor:0,totalPoints:0,lastSeasonPoints:0,last:null}}
function buildProfile(roomCode,gameNo){const profile=weightedProfile(roomCode,gameNo),startOvr=rint(roomCode+'|ovr|'+gameNo,profile.ovr[0],profile.ovr[1]),startPot=rint(roomCode+'|pot|'+gameNo,Math.max(startOvr+7,profile.pot[0]),profile.pot[1]);return {...profile,startOvr,startPot}}
function newRoom(roomCode,position,name){const gameNo=0,shared=buildProfile(roomCode,gameNo);return {code:roomCode,position,profile:shared,phase:'lobby',round:0,maxSeasons:MAX_SEASONS,players:[makePlayer(myPeerId,name,shared)],scenario:null,results:[],previousRanks:{},gameNo,created:Date.now()}}
function peerReady(){return typeof window.Peer==='function'}
function wireConnection(conn,hostSide){connections.set(conn.peer,conn);conn.on('data',data=>hostSide?handleHostData(conn,data):handleClientData(data));conn.on('close',()=>{connections.delete(conn.peer);if(hostSide&&localState){const p=localState.players.find(x=>x.id===conn.peer);if(p){if(localState.phase==='lobby')localState.players=localState.players.filter(x=>x.id!==conn.peer);else p.connected=false;publish()}}else if(!hostSide)notice('The host disconnected. The room has ended.',true)});conn.on('error',()=>notice('A player connection was interrupted.',true))}
function createRoom(){myName=cleanName($('#hostName').value);if(!myName)return notice('Enter your nickname first.',true);if(!peerReady())return notice('Multiplayer is still loading. Try again.',true);isHost=true;const roomCode=code();peer=new Peer(ROOM_PREFIX+roomCode.toLowerCase(),{debug:1});peer.on('open',id=>{myPeerId=id;localState=newRoom(roomCode,$('#sharedPosition').value,myName);setScreen('lobby');render();notice('Room created. Share the code.');window.flTrack?.('Multiplayer Room Created')});peer.on('connection',conn=>wireConnection(conn,true));peer.on('error',err=>{if(err?.type==='unavailable-id'){peer.destroy();createRoom()}else notice('The room could not connect. Please try again.',true)})}
function joinRoom(){myName=cleanName($('#joinName').value);const roomCode=$('#roomCodeInput').value.toUpperCase().replace(/[^A-Z2-9]/g,'').slice(0,5);if(!myName)return notice('Enter your nickname first.',true);if(roomCode.length!==5)return notice('Enter the five-character room code.',true);if(!peerReady())return notice('Multiplayer is still loading. Try again.',true);isHost=false;peer=new Peer(undefined,{debug:1});peer.on('open',id=>{myPeerId=id;hostConnection=peer.connect(ROOM_PREFIX+roomCode.toLowerCase(),{reliable:true});wireConnection(hostConnection,false);hostConnection.on('open',()=>{send(hostConnection,{type:'join',name:myName});notice('Connected to room.');window.flTrack?.('Multiplayer Room Joined')});setTimeout(()=>{if(!hostConnection.open)notice('Room not found. Check the code and host connection.',true)},7000)});peer.on('error',()=>notice('The room could not connect. Check the code.',true))}
function handleHostData(conn,data){if(!data||typeof data.type!=='string')return;if(data.type==='join'){if(localState.phase!=='lobby')return send(conn,{type:'error',message:'This career has already started.'});if(localState.players.length>=MAX_PLAYERS)return send(conn,{type:'error',message:'This room is full.'});const name=cleanName(data.name)||'Player';if(!localState.players.some(p=>p.id===conn.peer))localState.players.push(makePlayer(conn.peer,name,localState.profile));publish()}else if(data.type==='choice'){if(localState.phase!=='choice')return;const p=localState.players.find(x=>x.id===conn.peer),index=Number(data.index);if(p&&Number.isInteger(index)&&index>=0&&index<localState.scenario.options.length&&p.choice==null){p.choice=index;publish();scheduleRevealIfReady()}}else if(data.type==='reaction'){relayReaction(cleanName(localState.players.find(x=>x.id===conn.peer)?.name)||'Player',String(data.emoji||'').slice(0,3))}}
function handleClientData(data){if(data?.type==='state'&&data.room){const previousRound=localState?.round,previousPhase=localState?.phase;localState=data.room;setScreen(localState.phase==='lobby'?'lobby':'game');if(localState.phase!=='choice'||previousRound!==localState.round||previousPhase!==localState.phase){choiceSent=false;selectedChoice=null}render()}else if(data?.type==='reaction')showReaction(data.name,data.emoji);else if(data?.type==='error')notice(data.message||'The room could not be joined.',true)}
function startGame(){if(!isHost||localState.players.length<2)return notice('At least two players are needed.',true);localState.round=1;localState.phase='choice';localState.scenario=scenarioFor(1);localState.players.forEach(p=>p.choice=null);localState.results=[];localState.previousRanks=currentRanks();publish();window.flTrack?.('Multiplayer Career Started')}
function scenarioFor(round){if(round===3||round===7)return SCENARIOS[3];if(round===10)return SCENARIOS[9];const pool=SCENARIOS.map((x,i)=>i).filter(i=>![3,9].includes(i));return SCENARIOS[pool[(hash(localState.code+'|scenario|'+localState.gameNo+'|'+round)+round)%pool.length]]}
function submitChoice(index){if(!localState||localState.phase!=='choice'||choiceSent)return;choiceSent=true;selectedChoice=index;if(isHost){const me=localState.players.find(p=>p.id===myPeerId);if(me&&me.choice==null)me.choice=index;publish();scheduleRevealIfReady()}else{send(hostConnection,{type:'choice',index});render()}}
function connectedPlayers(){return localState.players.filter(p=>p.connected!==false)}
function allReady(){return connectedPlayers().length>=2&&connectedPlayers().every(p=>p.choice!=null)}
function scheduleRevealIfReady(){if(!isHost||!allReady()||revealTimer)return;revealTimer=setTimeout(()=>{revealTimer=null;revealSeason()},900)}
function grade(avg){return avg>=8?'A+':avg>=7.65?'A':avg>=7.3?'B+':avg>=6.95?'B':avg>=6.65?'C+':avg>=6.35?'C':'D'}
function verdict(score){return score>=.62?'EXCELLENT CHOICE':score>=.27?'GOOD CHOICE':score>=-.04?'MIXED CHOICE':'POOR CHOICE'}
function transferOfferFor(p,round){const current=clubTier(p.club),target=Math.min(95,Math.max(current+3,p.ovr+4)),candidates=CLUBS.filter(c=>c.name!==p.club&&c.tier>=current+2).sort((a,b)=>Math.abs(a.tier-target)-Math.abs(b.tier-target));if(!candidates.length)return CLUBS[CLUBS.length-1];return candidates[hash(`${localState.code}|offer|${localState.gameNo}|${round}|${p.id}`)%Math.min(4,candidates.length)]}
function chooseAward(p,avg,goals,assists,key){const output=goals+assists,position=localState.position;if(p.age<=21&&avg>=7.15&&rng(key+'|breakthrough')<.20)return 'Breakthrough Award';if(avg>=7.35&&rng(key+'|tots')<clamp(.08+(avg-7.3)*.28,.05,.34))return 'Team of the Season';if(['ST','WG'].includes(position)&&goals>=24&&rng(key+'|boot')<clamp(.10+(goals-24)*.012,.10,.50))return 'Golden Boot';if(avg>=7.7&&output>=Math.max(12,position==='ST'?25:position==='WG'?20:position==='CM'?14:6)&&rng(key+'|pos')<clamp(.07+(avg-7.65)*.30,.07,.38))return 'Player of the Season';return null}
function seasonScoreParts(r){const awards=r.awardName?AWARD_POINTS[r.awardName]||0:0;return {goals:r.goals*POINTS.goal,assists:r.assists*POINTS.assist,domesticCup:r.domesticCup?POINTS.domesticCup:0,leagueTitle:r.leagueTitle?POINTS.leagueTitle:0,continentalClub:r.continentalClub?POINTS.continentalClub:0,internationalCountry:r.internationalCountry?POINTS.internationalCountry:0,awards,ballonDor:r.ballonDor?POINTS.ballonDor:0}}
function pointsTotal(parts){return Object.values(parts).reduce((a,b)=>a+b,0)}
function simulatePlayer(p){const sc=localState.scenario,index=p.choice==null?1:p.choice,opt=sc.options[index],key=`${localState.code}|${localState.gameNo}|${localState.round}|${p.id}|${index}`,luck=(rng(key+'|luck')*2-1)*opt.swing,decision=opt.base+luck,age=p.age,gap=Math.max(0,p.pot-p.ovr),natural=age<=20?1.7+gap*.075:age<=23?1.15+gap*.055:age<=26?.65+gap*.035:age<=29?.18:age<=31?-.25:-.75,growth=Math.round(natural*localState.profile.growth+decision*2.1+(opt.dev||0));let delta=clamp(growth,age<=23?-1:-2,age<=23?6:4),projected=p.ovr+delta;if(projected>p.pot){if(decision>=.24&&age<=29)p.pot=clamp(projected+(decision>=.75?2:decision>=.46?1:0),p.pot,99);else{delta=p.pot-p.ovr;projected=p.pot}}if(p.pot-p.ovr<=2&&decision>=.38&&age<=29)p.pot=clamp(Math.max(p.pot,projected+1),p.pot,99);p.ovr=clamp(projected,48,p.pot);p.peak=Math.max(p.peak,p.ovr);
 let transferText='',transferSuccess=false;if(opt.transfer){const offer=transferOfferFor(p,localState.round),threshold=index===1?.28:.06;if(decision>=threshold&&offer.tier>clubTier(p.club)){const old=p.club;p.club=offer.name;transferSuccess=true;transferText=`${old} → ${offer.name}`}}
 const level=clubTier(p.club),competitionPenalty=Math.max(0,(level-p.ovr)*.20),baseApps=31+Math.round((p.ovr-62)*.24)+(opt.apps||0)-competitionPenalty+rint(key+'|apps',-4,5),apps=clamp(Math.round(baseApps),10,49),rates={ST:[.48,.16],WG:[.29,.27],CM:[.14,.25],CB:[.055,.075],GK:[.002,.025]}[localState.position],quality=clamp(.72+(p.ovr-55)/55,.7,1.55),attackBoost=1+(opt.attack||0)+(decision*.11),historicProb=.00035+(localState.profile.historic||0)+({epic:.001,legendary:.004,mythic:.012}[localState.profile.rarity]||0),historic=p.ovr>=85&&age>=20&&rng(key+'|historic')<historicProb;let goals=Math.max(0,Math.round(apps*rates[0]*quality*attackBoost*(.76+rng(key+'|goals')*.48))),assists=Math.max(0,Math.round(apps*rates[1]*quality*attackBoost*(.76+rng(key+'|assists')*.48)));if(historic){if(['ST','WG'].includes(localState.position)){const total=48+rint(key+'|era',0,20),share=localState.position==='ST'?.66:.52;goals=Math.max(goals,Math.round(total*share));assists=Math.max(assists,total-goals)}else if(localState.position==='CM'){const total=29+rint(key+'|era',0,17);goals=Math.max(goals,Math.round(total*.34));assists=Math.max(assists,total-goals)}}
 const avg=clamp(6.62+(p.ovr-65)*.014+decision*.28+(goals+assists)/Math.max(20,apps)*.10+(historic?.82:0),5.8,9.15),clubPower=clamp((level-62)/33,0,1),teamBoost=(opt.trophy||0)+Math.max(0,decision)*.04,domesticCup=rng(key+'|cup')<clamp(.055+clubPower*.13+teamBoost,.025,.31),leagueTitle=rng(key+'|league')<clamp(.025+clubPower*.15+teamBoost*.75,.008,.28),continentalClub=level>=82&&rng(key+'|continental')<clamp(.006+clubPower*.105+Math.max(0,decision)*.018,.003,.18),internationalWindow=[3,7].includes(localState.round),internationalCountry=internationalWindow&&p.ovr>=77&&rng(key+'|intl')<clamp(.018+(p.ovr-77)*.004+(opt.international||0),.01,.17),awardName=chooseAward(p,avg,goals,assists,key),ballonPower=(avg-6.5)*22+(goals+assists)*.72+p.ovr*.31+(continentalClub?16:0)+(internationalCountry?20:0)+(leagueTitle?8:0)+(awardName==='Player of the Season'?12:0)+(awardName==='Golden Boot'?10:0);
 p.apps+=apps;p.goals+=goals;p.assists+=assists;if(domesticCup)p.trophies.domesticCup++;if(leagueTitle)p.trophies.leagueTitle++;if(continentalClub)p.trophies.continentalClub++;if(internationalCountry)p.trophies.internationalCountry++;if(awardName)p.awards.push({season:localState.round,name:awardName});p.age++;
 const result={id:p.id,name:p.name,choice:index,choiceLabel:opt.label,verdict:verdict(decision),score:decision,apps,goals,assists,avg:+avg.toFixed(2),grade:grade(avg),delta,domesticCup,leagueTitle,continentalClub,internationalCountry,awardName,ballonDor:false,ballonPower,historic,club:p.club,transferSuccess,transferText,effect:`${opt.label} ${decision>=.62?'transformed the season':decision>=.27?'gave you an edge':decision>=-.04?'produced mixed results':'did not pay off this time'}.${transferSuccess?' The transfer changed your level and future trophy chances.':''}`};
 p.last=result;return result}
function assignBallonDor(results){const eligible=results.filter(r=>r.ballonPower>=62&&localState.players.find(p=>p.id===r.id)?.ovr>=84).sort((a,b)=>b.ballonPower-a.ballonPower);if(!eligible.length)return;const best=eligible[0],chance=clamp(.05+(best.ballonPower-62)*.009,.05,.56);if(rng(`${localState.code}|${localState.gameNo}|${localState.round}|ballon`)<chance){best.ballonDor=true;const p=localState.players.find(x=>x.id===best.id);if(p)p.ballonDor++}}
function currentRanks(){const sorted=[...localState.players].sort((a,b)=>b.totalPoints-a.totalPoints||b.peak-a.peak||a.name.localeCompare(b.name)),map={};sorted.forEach((p,i)=>map[p.id]=i+1);return map}
function revealSeason(){if(!isHost||localState.phase!=='choice')return;for(const p of localState.players)if(p.choice==null)p.choice=1;localState.previousRanks=currentRanks();let results=localState.players.map(simulatePlayer);assignBallonDor(results);for(const r of results){const parts=seasonScoreParts(r),seasonPoints=pointsTotal(parts),p=localState.players.find(x=>x.id===r.id);p.lastSeasonPoints=seasonPoints;p.totalPoints+=seasonPoints;r.points=parts;r.seasonPoints=seasonPoints;r.totalPoints=p.totalPoints;r.previousTotal=p.totalPoints-seasonPoints;r.ovr=p.ovr;r.pot=p.pot;r.peak=p.peak}results.sort((a,b)=>b.seasonPoints-a.seasonPoints||b.avg-a.avg||b.goals+b.assists-(a.goals+a.assists));localState.results=results;localState.phase='breakdown';publish()}
function showSeasonLeaderboard(){if(!isHost||localState.phase!=='breakdown')return;localState.phase='leaderboard';publish()}
function nextSeason(){if(!isHost||localState.phase!=='leaderboard'||localState.round>=MAX_SEASONS)return;localState.round++;localState.phase='choice';localState.scenario=scenarioFor(localState.round);localState.results=[];localState.players.forEach(p=>p.choice=null);choiceSent=false;publish()}
function showFinal(){if(!isHost||localState.phase!=='leaderboard'||localState.round<MAX_SEASONS)return;localState.phase='final';publish();window.flTrack?.('Multiplayer Career Completed')}
function playAgainSameParty(){if(!isHost||localState.phase!=='final')return;localState.gameNo=(localState.gameNo||0)+1;localState.profile=buildProfile(localState.code,localState.gameNo);localState.players=localState.players.filter(p=>p.connected!==false).map(p=>makePlayer(p.id,p.name,localState.profile));localState.round=1;localState.phase='choice';localState.scenario=scenarioFor(1);localState.results=[];localState.previousRanks=currentRanks();choiceSent=false;selectedChoice=null;publish();notice('New career started with the same party.')}
function relayReaction(name,emoji){if(!['🔥','😱','👏','😂'].includes(emoji))return;broadcast({type:'reaction',name,emoji});showReaction(name,emoji)}
function react(emoji){if(isHost)relayReaction(myName,emoji);else send(hostConnection,{type:'reaction',emoji})}
function showReaction(name,emoji){const layer=$('#reactionLayer'),el=document.createElement('div');el.className='mpReactionPop';el.style.setProperty('--drift',Math.random());el.innerHTML=`${esc(emoji)}<small>${esc(name)}</small>`;layer.appendChild(el);setTimeout(()=>el.remove(),1900)}
function copyCode(){navigator.clipboard?.writeText(localState.code).then(()=>notice('Room code copied.')).catch(()=>notice(`Room code: ${localState.code}`))}
function playerRows(showReady=false){const list=showReady?localState.players:[...localState.players].sort((a,b)=>b.totalPoints-a.totalPoints||b.peak-a.peak);return list.map((p,i)=>showReady?`<div class="mpPlayer"><div class="mpAvatar">${esc(initials(p.name))}</div><div><b>${esc(p.name)}${p.id===myPeerId?' • You':''}</b><small>${p.id===localState.players[0].id?'HOST • ':''}${p.connected===false?'DISCONNECTED':(p.choice!=null||p.ready)?'CHOICE LOCKED':'READY TO PLAY'}</small></div><i class="mpReady ${p.choice!=null||p.ready?'on':''}"></i></div>`:`<div class="mpLeaderRow ${p.id===myPeerId?'you':''}"><div class="mpRank">${i+1}</div><div><b>${esc(p.name)}${p.id===myPeerId?' • You':''}</b><small>${esc(p.club)}</small></div><div class="mpMetric"><strong>${p.totalPoints.toLocaleString()}</strong><span>POINTS</span></div><div class="mpMetric"><strong>${p.ovr}</strong><span>OVR</span></div><div class="mpMetric mpHideMobile"><strong>${p.peak}</strong><span>PEAK</span></div><div class="mpMetric mpHideMobile"><strong>${p.ballonDor||0}</strong><span>BALLON D'OR</span></div></div>`).join('')}
function profileCard(){const p=localState.profile;return `<div class="mpCard mpProfile rarity-${p.rarity}"><div class="mpProfileTop"><div><div class="mpEyebrow">SHARED CAREER PROFILE</div><h2>${esc(p.name)}</h2><div class="mpRarity">${esc(p.rarity)} • ${p.chance}% profile</div></div><div class="mpProfileOvr">${p.startOvr}<small>START OVR</small></div></div><div class="mpNote">Everyone starts from the same career conditions for a fair race. Season points stay sealed until the reveal.</div></div>`}
function pointsPreview(){return `<div class="mpCard mpPointsPreview"><div class="mpPreviewHead"><div><div class="mpEyebrow">HOW POINTS WORK</div><h2>Big achievements matter.</h2></div><span>PREVIEW</span></div><div class="mpPointRules"><div><b>Goal</b><strong>+${POINTS.goal}</strong></div><div><b>Assist</b><strong>+${POINTS.assist}</strong></div><div><b>Domestic cup</b><strong>+${POINTS.domesticCup}</strong></div><div><b>League title</b><strong>+${POINTS.leagueTitle}</strong></div><div><b>Continental club trophy</b><strong>+${POINTS.continentalClub}</strong></div><div><b>International country trophy</b><strong>+${POINTS.internationalCountry.toLocaleString()}</strong></div><div><b>Major award</b><strong>+120–450</strong></div><div class="gold"><b>Ballon d'Or</b><strong>+${POINTS.ballonDor.toLocaleString()}</strong></div></div><div class="mpNote">Only one Ballon d'Or can be awarded across the party in a season. A goal and assist are equal; the hardest achievements are worth dramatically more.</div></div>`}
function renderLobby(){const b=$('#lobby');b.innerHTML=`<div class="mpLobbyHead"><div><div class="mpEyebrow">WAITING ROOM</div><h1>${localState.players.length} of ${MAX_PLAYERS} players</h1></div><button class="mpRoomCode" id="copyRoom"><small>TAP TO COPY</small><strong>${localState.code}</strong></button></div>${profileCard()}<div class="mpCard"><div class="mpEyebrow">PLAYERS</div><div class="mpPlayerGrid" style="margin-top:10px">${playerRows(true)}</div>${isHost?`<button id="startGame" class="mpPrimary mpLobbyAction" ${localState.players.length<2?'disabled':''}>Start Career</button><div class="mpNote">Share one code. Nobody needs an account.</div>`:'<div class="mpWaiting">Waiting for the host to start…</div>'}</div>${pointsPreview()}`;$('#copyRoom').onclick=copyCode;$('#startGame')?.addEventListener('click',startGame)}
function reactionBar(){return `<div class="mpReactionBar"><span>React</span>${['🔥','😱','👏','😂'].map(x=>`<button data-react="${x}" aria-label="React ${x}">${x}</button>`).join('')}</div>`}
function renderChoice(){const b=$('#game'),sc=localState.scenario,me=localState.players.find(p=>p.id===myPeerId),ready=me?.choice!=null||me?.ready||choiceSent,readyCount=connectedPlayers().filter(p=>p.choice!=null||p.ready).length,offer=sc.transfer&&me?transferOfferFor(me,localState.round):null;b.innerHTML=`<div class="mpGameTop"><div><div class="mpRound">SEASON ${localState.round} OF ${MAX_SEASONS}</div><h2>${2026+localState.round-1}/${String(2027+localState.round-1).slice(-2)}</h2></div><div class="mpRoomCode"><small>ROOM</small><strong>${localState.code}</strong></div></div><div class="mpCareerStrip"><div><small>YOU</small><b>${esc(me?.name||myName)}</b></div><div><small>CLUB</small><b>${esc(me?.club||'Hometown FC')}</b></div><div><small>OVR</small><b>${me?.ovr??localState.profile.startOvr}</b></div><div class="sealed"><small>SEASON SCORE</small><b>SEALED</b></div></div><div class="mpCard mpScenario"><div class="mpEyebrow">${sc.icon} CAREER DECISION</div><h1>${esc(sc.title)}</h1><p>${esc(sc.text)}</p>${offer?`<div class="mpTransferOffer"><small>YOUR OFFER</small><b>${esc(offer.name)}</b><span>Club level ${offer.tier} • current club ${clubTier(me.club)}</span></div>`:''}<div class="mpChoices">${sc.options.map((o,i)=>`<button class="mpChoice ${(me?.choice===i||selectedChoice===i)?'selected':''}" data-choice="${i}" ${ready?'disabled':''}><b>${esc(o.label)}</b><span>${esc(o.hint)}</span></button>`).join('')}</div>${ready?'<div class="mpWaiting">Choice locked. Your season stats and points remain hidden until everyone is ready.</div>':''}</div><div class="mpCard"><div class="mpLobbyHead"><div><div class="mpEyebrow">DECISIONS LOCKED</div><h2>${readyCount} / ${connectedPlayers().length} ready</h2></div></div><div class="mpPlayerGrid">${playerRows(true)}</div>${isHost&&allReady()?'<button id="revealNow" class="mpPrimary">Reveal Season</button>':''}</div><div class="mpMystery"><b>?</b><div><strong>No live leaderboard.</strong><span>Current-season goals, assists, trophies, awards and points are hidden until the shared reveal.</span></div></div>${reactionBar()}`;b.querySelectorAll('[data-choice]').forEach(x=>x.onclick=()=>submitChoice(+x.dataset.choice));$('#revealNow')?.addEventListener('click',revealSeason);wireReactions(b)}
function sleep(ms){return new Promise(resolve=>setTimeout(resolve,ms))}
function reducedMotion(){return !!window.matchMedia?.('(prefers-reduced-motion: reduce)').matches}
function cinematicCurrent(run,phase){return run===cinematicRun&&localState?.phase===phase}
function animateNumber(el,from,to,duration,run,phase,prefix=''){
 return new Promise(resolve=>{if(!el){resolve();return}if(reducedMotion()||duration<=0){el.textContent=prefix+Math.round(to).toLocaleString();resolve();return}const began=performance.now(),diff=to-from;function frame(now){if(!cinematicCurrent(run,phase)){resolve();return}const t=Math.min(1,(now-began)/duration),ease=1-Math.pow(1-t,3),value=Math.round(from+diff*ease);el.textContent=prefix+value.toLocaleString();if(t<1)requestAnimationFrame(frame);else resolve()}requestAnimationFrame(frame)})
}
function metricCell(r,key,rowIndex,playerIndex){const parts=r.points||{},raw={goals:r.goals,assists:r.assists,domesticCup:r.domesticCup?'1 trophy':'—',leagueTitle:r.leagueTitle?'1 title':'—',continentalClub:r.continentalClub?'1 trophy':'—',internationalCountry:r.internationalCountry?'1 trophy':'—',awards:r.awardName||'—',ballonDor:r.ballonDor?'WINNER':'—'}[key],pts=parts[key]||0;return `<div class="mpRevealCell mpRevealTarget ${pts?'earned':''}" data-reveal-row="${rowIndex}" data-player-id="${esc(r.id)}" data-player-index="${playerIndex}" data-points="${pts}"><strong>?</strong><small>${esc(raw)}</small></div>`}
function breakdownGrid(){const players=localState.players.map(p=>localState.results.find(r=>r.id===p.id)).filter(Boolean),rows=[['goals','Goals'],['assists','Assists'],['domesticCup','Domestic cup'],['leagueTitle','League title'],['continentalClub','Continental club'],['internationalCountry','International country'],['awards','Awards'],['ballonDor',"Ballon d'Or"]];return `<div class="mpBreakdownWrap" style="--players:${players.length}"><div class="mpBreakdownViewport" id="breakdownViewport"><div class="mpRevealGrid"><div class="mpRevealCorner">POINTS</div>${players.map(p=>`<div class="mpRevealName" data-player-id="${esc(p.id)}"><span>${esc(initials(p.name))}</span><b>${esc(p.name)}</b></div>`).join('')}${rows.map(([key,label],row)=>`<div class="mpRevealLabel mpRevealTarget" data-reveal-row="${row}">${label}</div>${players.map((p,i)=>metricCell(p,key,row,i)).join('')}`).join('')}<div class="mpRevealLabel total mpRevealTarget" data-reveal-row="8">SEASON TOTAL</div>${players.map((p,i)=>`<div class="mpRevealCell total mpRevealTarget" data-reveal-row="8" data-player-id="${esc(p.id)}" data-player-index="${i}" data-points="${p.seasonPoints}"><strong>?</strong><small>points</small></div>`).join('')}</div></div></div>`}
function revealBreakdownRow(row,run){const phase='breakdown',viewport=$('#breakdownViewport'),items=[...document.querySelectorAll(`[data-reveal-row="${row}"]`)];if(!items.length)return Promise.resolve();const label=items[0];if(viewport&&label){const top=Math.max(0,label.offsetTop-viewport.clientHeight*.40);viewport.scrollTo({top,behavior:reducedMotion()?'auto':'smooth'})}return Promise.all(items.map(async(el,i)=>{await sleep(reducedMotion()?0:i===0?0:Math.min(275,(i-1)*55));if(!cinematicCurrent(run,phase))return;el.classList.add('revealed');el.setAttribute('aria-hidden','false');if(el.classList.contains('mpRevealCell')){const pts=+(el.dataset.points||0),strong=el.querySelector('strong');if(pts>0)await animateNumber(strong,0,pts,reducedMotion()?0:330,run,phase,'+');else if(strong)strong.textContent='—'}}))}
async function startBreakdownCinematic(){const run=++cinematicRun,phase='breakdown',winner=localState.results[0],labels=['GOALS','ASSISTS','DOMESTIC CUP','LEAGUE TITLE','CONTINENTAL CLUB','INTERNATIONAL COUNTRY','AWARDS',"BALLON D'OR",'SEASON TOTAL'],delays=[300,300,420,500,580,650,520,800,950],status=$('#cinematicStatus'),progress=$('#cinematicProgress');await sleep(reducedMotion()?20:450);for(let row=0;row<labels.length;row++){if(!cinematicCurrent(run,phase))return;if(status)status.textContent=row===8?'Everything comes down to the total…':`${labels[row]} • revealing for everyone`;if(progress)progress.style.width=`${((row+1)/labels.length)*100}%`;await revealBreakdownRow(row,run);if(!cinematicCurrent(run,phase))return;await sleep(reducedMotion()?20:delays[row])}if(!cinematicCurrent(run,phase))return;document.querySelectorAll(`[data-player-id="${CSS.escape(winner.id)}"]`).forEach(x=>x.classList.add('winnerColumn'));const title=$('#seasonRevealTitle'),score=$('#seasonTopScore'),champ=$('#seasonBestReveal');if(title)title.textContent=`${winner.name} wins Season ${localState.round}`;if(score){score.textContent=winner.seasonPoints.toLocaleString();score.closest('.mpSeasonWinner')?.classList.add('revealed')}if(status)status.textContent='SEASON WINNER';if(champ){champ.innerHTML=`<span>★ SEASON ${localState.round} WINNER</span><strong>${esc(winner.name)}</strong><b>${winner.seasonPoints.toLocaleString()} points</b>`;champ.classList.add('show')}await sleep(reducedMotion()?60:1700);if(cinematicCurrent(run,phase)&&isHost)showSeasonLeaderboard()}
function renderBreakdown(){const b=$('#game'),winner=localState.results[0],mine=localState.results.find(x=>x.id===myPeerId)||winner,ballon=localState.results.find(x=>x.ballonDor);b.innerHTML=`<div class="mpGameTop"><div><div class="mpRound">SEASON ${localState.round} POINT REVEAL</div><h2 id="seasonRevealTitle">Nobody knows who won yet.</h2></div><div class="mpSeasonWinner"><small>TOP SCORE</small><strong id="seasonTopScore">SEALED</strong></div></div><div class="mpCard mpRevealIntro"><div><div class="mpEyebrow">THE SEALED ENVELOPE IS OPEN</div><h1>Watch the season unfold.</h1><p>Your choice was <b>${esc(mine.choiceLabel)}</b>. Its effect and every point stay part of the same shared reveal.</p><div class="mpCinematicStatus"><span id="cinematicStatus">Preparing the first category…</span><i><b id="cinematicProgress"></b></i></div></div></div>${breakdownGrid()}<div id="seasonBestReveal" class="mpSeasonBestReveal" aria-live="polite"></div>${ballon?`<div class="mpBallonMoment mpAfterReveal">🏆 If a Ballon d'Or appears above, it is the only one awarded across the entire party this season.</div>`:''}<div class="mpAutoCut">After the season winner is revealed, every screen automatically cuts to the overall leaderboard.</div>${reactionBar()}`;wireReactions(b);startBreakdownCinematic()}
function rankMovementMarkup(oldRank,newRank){const delta=oldRank-newRank;if(delta>0)return `<span class="mpMove up">▲ ${delta}</span>`;if(delta<0)return `<span class="mpMove down">▼ ${Math.abs(delta)}</span>`;return '<span class="mpMove same">—</span>'}
function currentRankMap(){const ordered=[...localState.players].sort((a,b)=>b.totalPoints-a.totalPoints||b.peak-a.peak||a.name.localeCompare(b.name)),map={};ordered.forEach((p,i)=>map[p.id]=i+1);return map}
function leaderboardRows(){const ranks=currentRankMap(),previous=localState.previousRanks||{},oldOrder=[...localState.players].sort((a,b)=>(previous[a.id]||99)-(previous[b.id]||99)||a.name.localeCompare(b.name));return oldOrder.map(p=>{const oldRank=previous[p.id]||ranks[p.id],newRank=ranks[p.id],before=p.totalPoints-p.lastSeasonPoints;return `<div class="mpScoreRow ${p.id===myPeerId?'you':''}" data-player="${esc(p.id)}" data-old-rank="${oldRank}" data-current-rank="${newRank}" data-before="${before}" data-after="${p.totalPoints}" data-gain="${p.lastSeasonPoints}"><div class="mpScoreRank"><strong>${oldRank}</strong><span class="mpMovePending">•</span></div><div class="mpScoreIdentity"><b>${esc(p.name)}${p.id===myPeerId?' • You':''}</b><small>${esc(p.club)} • ${p.ovr} OVR</small></div><div class="mpSeasonGain"><span class="mpGainValue">+0</span><small>THIS SEASON</small></div><div class="mpScoreTick"><span>${before.toLocaleString()}</span><i>+</i><strong class="mpLiveTotal">${before.toLocaleString()}</strong></div></div>`}).join('')}
function flipLeaderboardToFinal(run){const list=$('.mpScoreList');if(!list)return Promise.resolve();const rows=[...list.querySelectorAll('.mpScoreRow')],first=new Map(rows.map(r=>[r,r.getBoundingClientRect().top]));rows.sort((a,b)=>+a.dataset.currentRank-+b.dataset.currentRank).forEach(r=>list.appendChild(r));const last=new Map(rows.map(r=>[r,r.getBoundingClientRect().top]));rows.forEach(r=>{const dy=(first.get(r)||0)-(last.get(r)||0);r.style.transition='none';r.style.transform=`translateY(${dy}px)`;r.querySelector('.mpScoreRank strong').textContent=r.dataset.currentRank;r.querySelector('.mpMovePending').outerHTML=rankMovementMarkup(+r.dataset.oldRank,+r.dataset.currentRank)});void list.offsetHeight;rows.forEach(r=>{r.classList.add('rankMoving');r.style.transition=reducedMotion()?'none':'transform 900ms cubic-bezier(.2,.82,.2,1), border-color 500ms, background 500ms';r.style.transform='translateY(0)'});return sleep(reducedMotion()?20:980).then(()=>{if(!cinematicCurrent(run,'leaderboard'))return;rows.forEach((r,i)=>{r.style.transition='';r.style.transform='';r.classList.remove('rankMoving');if(i===0)r.classList.add('leader')})})}
async function startLeaderboardCinematic(){const run=++cinematicRun,phase='leaderboard',rows=[...document.querySelectorAll('.mpScoreRow')],status=$('#leaderboardStatus');await sleep(reducedMotion()?20:500);if(status)status.textContent='Adding this season’s points…';await Promise.all(rows.map(async(r,i)=>{await sleep(reducedMotion()?0:i*90);if(!cinematicCurrent(run,phase))return;const gain=+r.dataset.gain,before=+r.dataset.before,after=+r.dataset.after;r.classList.add('counting');await Promise.all([animateNumber(r.querySelector('.mpGainValue'),0,gain,reducedMotion()?0:1100,run,phase,'+'),animateNumber(r.querySelector('.mpLiveTotal'),before,after,reducedMotion()?0:1450,run,phase)]);r.classList.remove('counting')}));if(!cinematicCurrent(run,phase))return;if(status)status.textContent='Recalculating the order…';await sleep(reducedMotion()?20:450);await flipLeaderboardToFinal(run);if(!cinematicCurrent(run,phase))return;const ordered=[...localState.players].sort((a,b)=>b.totalPoints-a.totalPoints||b.peak-a.peak||a.name.localeCompare(b.name)),overall=ordered[0],leaderBox=$('#overallLeaderBox');if(leaderBox){leaderBox.querySelector('small').textContent='OVERALL LEADER';leaderBox.querySelector('strong').textContent=initials(overall.name);leaderBox.classList.add('revealed')}if(status)status.textContent=`${overall.name} leads the career with ${overall.totalPoints.toLocaleString()} points.`;$('#leaderboardActions')?.classList.add('show');await sleep(reducedMotion()?20:300);document.querySelector('.mpScoreRow.leader')?.classList.add('leaderPulse')}
function renderLeaderboard(){const b=$('#game'),winner=localState.results[0];b.innerHTML=`<div class="mpGameTop"><div><div class="mpRound">SEASON ${localState.round} COMPLETE</div><h2>${esc(winner.name)} took the season. Now watch the table change.</h2></div><div class="mpRoomCode mpOverallLeader" id="overallLeaderBox"><small>CALCULATING</small><strong>•••</strong></div></div><div class="mpCard mpScoreboard"><div class="mpPreviewHead"><div><div class="mpEyebrow">OVERALL GAME LEADERBOARD</div><h1>Career points</h1></div><span>LIVE UPDATE</span></div><div class="mpLeaderboardStatus" id="leaderboardStatus">Loading the previous table…</div><div class="mpScoreList">${leaderboardRows()}</div></div><div id="leaderboardActions" class="mpLeaderboardActions">${isHost?(localState.round<MAX_SEASONS?`<button id="nextSeason" class="mpPrimary">Play Season ${localState.round+1}</button>`:'<button id="showFinal" class="mpPrimary">Reveal Final Winner</button>'):'<div class="mpWaiting">Waiting for the host after the leaderboard settles…</div>'}</div>${reactionBar()}`;$('#nextSeason')?.addEventListener('click',nextSeason);$('#showFinal')?.addEventListener('click',showFinal);wireReactions(b);startLeaderboardCinematic()}
function finalBurst(){const layer=$('#finalBurst');if(!layer)return;layer.innerHTML=Array.from({length:26},(_,i)=>`<i style="--i:${i};--x:${((i*47)%101)-50};--d:${(i%7)*.06}s"></i>`).join('');layer.classList.add('go')}
async function startFinalCinematic(){const run=++cinematicRun,phase='final',ordered=[...localState.players].sort((a,b)=>b.totalPoints-a.totalPoints||b.peak-a.peak||a.name.localeCompare(b.name)),winner=ordered[0],name=$('#finalWinnerName'),score=$('#finalWinnerScore');await sleep(reducedMotion()?20:650);if(!cinematicCurrent(run,phase))return;if(name){name.textContent=`${winner.name} wins Football Legacy`;name.classList.add('revealed')}finalBurst();await animateNumber(score,0,winner.totalPoints,reducedMotion()?0:1700,run,phase);if(!cinematicCurrent(run,phase))return;document.querySelectorAll('.mpPodium').forEach((p,i)=>setTimeout(()=>p.classList.add('rise'),reducedMotion()?0:i*180));await sleep(reducedMotion()?20:950);$('#finalDetails')?.classList.add('show')}
function renderFinal(){const b=$('#game'),ordered=[...localState.players].sort((a,b)=>b.totalPoints-a.totalPoints||b.peak-a.peak||a.name.localeCompare(b.name)),winner=ordered[0],podium=[ordered[1],ordered[0],ordered[2]].filter(Boolean);b.innerHTML=`<div class="mpCard mpFinalHero mpFinalCinematic"><div id="finalBurst" class="mpFinalBurst" aria-hidden="true"></div><div class="mpEyebrow">FINAL WHISTLE • ${MAX_SEASONS} SEASONS COMPLETE</div><h1 id="finalWinnerName">And the winner is…</h1><div class="mpFinalScore"><span id="finalWinnerScore">0</span><small>CAREER POINTS</small></div><div class="mpFinalPodium">${podium.map(p=>`<div class="mpPodium ${p===winner?'first':''}"><strong>${p===winner?'1':p===ordered[1]?'2':'3'}</strong><b>${esc(p.name)}</b><small>${p.totalPoints.toLocaleString()} pts • ${p.peak} peak</small></div>`).join('')}</div></div><div id="finalDetails" class="mpFinalDetails"><div class="mpCard"><div class="mpEyebrow">FINAL TABLE</div><div class="mpLeaderboard" style="margin-top:9px">${playerRows(false)}</div></div><div class="mpReplayZone"><div><div class="mpEyebrow">SAME PARTY. NEW CAREER.</div><h2>Play again instantly.</h2><p>No new code and no rejoining. Everyone who is still connected starts a fresh career together.</p></div>${isHost?'<button id="playAgainParty" class="mpPrimary">Play Again With Same Party</button>':'<div class="mpWaiting">The host can start another career with this party.</div>'}</div><a class="mpFeedbackLink" href="index.html#reviews-feedback">Finished playing? Leave feedback →</a>${reactionBar()}</div>`;$('#playAgainParty')?.addEventListener('click',playAgainSameParty);wireReactions(b);startFinalCinematic()}
function wireReactions(root){root.querySelectorAll('[data-react]').forEach(x=>x.onclick=()=>react(x.dataset.react))}
function render(){if(!localState)return;if(localState.phase==='lobby'){setScreen('lobby');renderLobby();return}setScreen('game');if(localState.phase==='choice')renderChoice();else if(localState.phase==='breakdown')renderBreakdown();else if(localState.phase==='leaderboard')renderLeaderboard();else renderFinal()}
function qaRun(playerCount=4,roomCode='QA7MX'){
 const keep={peer,isHost,myPeerId,myName,localState,choiceSent,selectedChoice,revealTimer};const failures=[];let hiddenChoices=true,ballonMax=0,scoreMismatch=0,transfers=0;
 try{isHost=true;myPeerId='qa-0';myName='Player 1';localState=newRoom(roomCode,'ST',myName);const count=clamp(Math.round(playerCount),2,MAX_PLAYERS);for(let i=1;i<count;i++)localState.players.push(makePlayer(`qa-${i}`,`Player ${i+1}`,localState.profile));localState.round=1;localState.phase='choice';localState.scenario=scenarioFor(1);
  for(let round=1;round<=MAX_SEASONS;round++){localState.round=round;localState.phase='choice';localState.scenario=scenarioFor(round);localState.results=[];localState.players.forEach((p,i)=>p.choice=(i+round)%localState.scenario.options.length);const concealed=publicRoom();if(concealed.players.some(p=>p.choice!==null)||concealed.players.some(p=>!p.ready))hiddenChoices=false;revealSeason();const bd=localState.results.filter(r=>r.ballonDor).length;ballonMax=Math.max(ballonMax,bd);if(bd>1)failures.push(`round ${round} awarded multiple Ballon d'Or winners`);for(const r of localState.results){if(r.seasonPoints!==pointsTotal(r.points))scoreMismatch++;if(r.transferSuccess)transfers++}localState.phase='leaderboard';if(round<MAX_SEASONS){localState.round++;localState.phase='choice'}}
  if(!hiddenChoices)failures.push('choice privacy failed');if(scoreMismatch)failures.push(`${scoreMismatch} score totals mismatched`);if(!transfers)failures.push('no transfer succeeded in QA run');return {ok:failures.length===0,failures,players:count,seasons:MAX_SEASONS,hiddenChoices,ballonMax,scoreMismatch,transfers,leader:[...localState.players].sort((a,b)=>b.totalPoints-a.totalPoints)[0]?.name};
 }finally{({peer,isHost,myPeerId,myName,localState,choiceSent,selectedChoice,revealTimer}=keep)}
}
window.FL_MULTIPLAYER_QA={run:qaRun,points:POINTS,awardPoints:AWARD_POINTS,profiles:PROFILES.map(({name,rarity,chance,w})=>({name,rarity,chance,w})),scenarioCount:SCENARIOS.length};
$('#createRoom').onclick=createRoom;$('#joinRoom').onclick=joinRoom;$('#roomCodeInput').addEventListener('input',e=>e.target.value=e.target.value.toUpperCase().replace(/[^A-Z2-9]/g,'').slice(0,5));$('#helpBtn').onclick=()=>$('#helpModal').hidden=false;$('#closeHelp').onclick=()=>$('#helpModal').hidden=true;$('#helpModal').addEventListener('click',e=>{if(e.target.id==='helpModal')e.currentTarget.hidden=true});
})();
